export const Jobs = [
    {
        image: "jp.jpeg",
        title: "Frontend Developer",
        company: "Jyllands-Posten ‧ Full-time",
        description: "I am working on the new platform for Jyllands-Posten, JP Lokal and Lokalavisen.",
        firstDate: "sep. 2020",
    },
    {
        image: "bleptek.jpeg",
        title: "Owner",
        company: "Bleptek ‧ Part-time",
        description: "A small project studio for side projects.",
        firstDate: "jan. 2021",
    },
    {
        image: "kruso.jpeg",
        title: "Frontend Developer (Lead)",
        company: "Kruso ‧ Full-time",
        description: "I was the frontend lead developer on one main project and other projects in the start-up phase. The job involved presentation and customer meetings, review, delegate issues and of course development of the projects. I decided to resign but still have a great relationship with the company.",
        firstDate: "jun. 2020",
        secondDate: "sep. 2020",
        durationMonths: 4,
    },
    {
        image: "novicell.jpeg",
        title: "Frontend Developer",
        company: "Novicell ‧ Full-time",
        description: "I was employed by Novicell for three weeks. They chose to cancel my contract due to an unknown length of my sick leave. I am perfectly well and healthy today.",
        firstDate: "feb. 2020",
        secondDate: "feb. 2020",
        durationMonths: 1,
    },
    {
        image: "jp.jpeg",
        title: "Web Developer",
        company: "Jyllands-Posten ‧ Full-time",
        description: "I worked as a web developer at Jyllands-Posten. My role was mainly focused around frontend development for the Watch Medier websites. My first task with the team was making the code for Watch Medier more component-based. Since then, I have been part of launching several websites, new components, concept development, implement continuous delivery, development on mobile sites and much more. I also helped with job interviews. I resigned my job to get more focus on front-end.",
        firstDate: "sep. 2017",
        secondDate: "feb. 2020",
        durationYears: 2,
        durationMonths: 6,
    },
    {
        image: "skybrud.jpeg",
        title: "Frontend Intern",
        company: "Skybrud ‧ Internship",
        description: "I had the honor of being a part of Skybrud.dk. Here, I learned a lot about the love for the craft and a deeper understanding of projects. They gave me insight into dealing with problem solving and the importance of empathy and communication.",
        firstDate: "jan. 2017",
        secondDate: "jul. 2017",
        durationMonths: 7,
    },
    {
        image: "happy.jpeg",
        title: "Founder",
        company: "Happy Bear Prints ‧ Part-time",
        description: "Happy Bear Prints is a project I started in 2014. It was a way I could improve my graphic design skills and communication with customers. I have since sold over 1300 posters in more than 40 countries. I have also appeared in magazines such as Marie Claire Idées, Sportswear International and Sweet Living Magazin.",
        firstDate: "2014",
        secondDate: "2017",
        durationYears: 3,
    },
    {
        image: "fokus.jpg",
        title: "Internship in own company",
        company: "Fokusfabrikken I/S ‧ Internship",
        description: "We created Fokusfabrikken I/S as part of our education at Business Academy Aarhus. It started as an internship in our own business, and we later used it for our graduating and since as a playground to find strengths and weaknesses. We have for the most part been developing websites, themes and plugins with WordPress. The company was registered from 2015 to 2018, but was mainly active in the beginning regarding the internship.",
        firstDate: "2015",
        secondDate: "2015",
        durationYears: 1,
    },
]